Finish ticket 5 plus add loading
BrokenRecord85/nc-games-frontend pull request #2
Opened 2022-09-26 15:03 UTC by BrokenRecord85

2022-09-26 15:12 UTC, leekli requested changes
Removing my original comment as it wasn't applicable.

2022-09-26 15:19 UTC, BrokenRecord85 commented
But that's ticket 6-view an individual review, I haven't done that yet,

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Lee Kirkham ***@***.***>
Sent: Monday, September 26, 2022 4:13:06 PM
To: BrokenRecord85/nc-games-frontend ***@***.***>
Cc: BrokenRecord85 ***@***.***>; Author ***@***.***>
Subject: Re: [BrokenRecord85/nc-games-frontend] Finish ticket 5 plus add loading (PR #2)


@leekli requested changes on this pull request.

Pawel - When I click on an individual review in my web browser, it doesn't load anything, it just takes me to a webpage of /reviews/:review_id

Can you have a look into this, I suspect one of the reasons is that there is not a route set up in App.js

I have not reviewed any other functionality yet as this key bit isn't working.

Once you have fixed this, then please submit a new PR request tomorrow (PRs close at 16:15pm today) and we will review it from scratch tomorrow.

—
Reply to this email directly, view it on GitHub<https://github.com/BrokenRecord85/nc-games-frontend/pull/2#pullrequestreview-1120422337>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A2EDB4S72IDEJ5AXXK2WLV3WAG4QFANCNFSM6AAAAAAQV4PAFE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-09-26 15:46 UTC, leekli requested changes
Apologies Pawel I was reading the wrong thing!

OK so I can see most of ticket 5 is implemented, one thing I'd like to see if some 'be some UI elements to navigate to each categories pages (links / dropdown etc.)' rather than having to only click the category under each article.

So some sort of component/page/list/drop down/whatever so a user can easily see a list of categories and click any to get them. Currently they would have to scroll through your reviews to try and find the category name they're looking for. 

Please have a look at implementing this, then submit a PR tomorrow for review

2022-09-26 15:46 UTC, leekli commented on src/utils/api.js
> +    console.log(category, 'API heeeeeeeeeeeeeeeeeeeeeeeerrree')
Let's remove this console log

2022-09-27 13:26 UTC, leekli approved these changes
Hi, as we've just been looking at this for an hour I'm happy to approve.

I've left 2 comments of lines which need removing through. You're free to merge.

2022-09-27 13:26 UTC, leekli commented on src/components/Categories.jsx
> +  console.log(params.category)
This console log to remove

2022-09-27 13:26 UTC, leekli commented on src/components/Categories.jsx
> +          //console.log(array)
Remove this line

2022-09-27 14:04 UTC, merged